package com.cn.umessage.dao.pms.jte.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IThirdpartyService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface IThirdpartyService {

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryUOrderAcc", action = "http://tempuri.org/IThirdpartyService/QueryUOrderAcc")
	@WebResult(name = "QueryUOrderAccResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryUOrderAcc", targetNamespace = "http://tempuri.org/", className = "com.jte.client.QueryUOrderAcc")
	@ResponseWrapper(localName = "QueryUOrderAccResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.QueryUOrderAccResponse")
	public String queryUOrderAcc(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOrder", action = "http://tempuri.org/IThirdpartyService/GetOrder")
	@WebResult(name = "GetOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOrder", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrder")
	@ResponseWrapper(localName = "GetOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrderResponse")
	public String getOrder(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOrderNew", action = "http://tempuri.org/IThirdpartyService/GetOrderNew")
	@WebResult(name = "GetOrderNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOrderNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrderNew")
	@ResponseWrapper(localName = "GetOrderNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrderNewResponse")
	public String getOrderNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "InsertMemberGuest", action = "http://tempuri.org/IThirdpartyService/InsertMemberGuest")
	@WebResult(name = "InsertMemberGuestResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "InsertMemberGuest", targetNamespace = "http://tempuri.org/", className = "com.jte.client.InsertMemberGuest")
	@ResponseWrapper(localName = "InsertMemberGuestResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.InsertMemberGuestResponse")
	public String insertMemberGuest(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMember", action = "http://tempuri.org/IThirdpartyService/GetMember")
	@WebResult(name = "GetMemberResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMember", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMember")
	@ResponseWrapper(localName = "GetMemberResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMemberResponse")
	public String getMember(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMemberType", action = "http://tempuri.org/IThirdpartyService/GetMemberType")
	@WebResult(name = "GetMemberTypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMemberType", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMemberType")
	@ResponseWrapper(localName = "GetMemberTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMemberTypeResponse")
	public String getMemberType(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param money
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMemberMoney", action = "http://tempuri.org/IThirdpartyService/SetMemberMoney")
	@WebResult(name = "SetMemberMoneyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMemberMoney", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberMoney")
	@ResponseWrapper(localName = "SetMemberMoneyResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberMoneyResponse")
	public String setMemberMoney(
			@WebParam(name = "money", targetNamespace = "http://tempuri.org/") String money);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetExchange", action = "http://tempuri.org/IThirdpartyService/SetExchange")
	@WebResult(name = "SetExchangeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetExchange", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchange")
	@ResponseWrapper(localName = "SetExchangeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeResponse")
	public String setExchange(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetActive", action = "http://tempuri.org/IThirdpartyService/SetActive")
	@WebResult(name = "SetActiveResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetActive", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetActive")
	@ResponseWrapper(localName = "SetActiveResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetActiveResponse")
	public String setActive(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMemberCoustomer", action = "http://tempuri.org/IThirdpartyService/SetMemberCoustomer")
	@WebResult(name = "SetMemberCoustomerResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMemberCoustomer", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberCoustomer")
	@ResponseWrapper(localName = "SetMemberCoustomerResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberCoustomerResponse")
	public String setMemberCoustomer(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetExchangeMemberCardNo", action = "http://tempuri.org/IThirdpartyService/SetExchangeMemberCardNo")
	@WebResult(name = "SetExchangeMemberCardNoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetExchangeMemberCardNo", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberCardNo")
	@ResponseWrapper(localName = "SetExchangeMemberCardNoResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberCardNoResponse")
	public String setExchangeMemberCardNo(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetExchangeMemberCancel", action = "http://tempuri.org/IThirdpartyService/SetExchangeMemberCancel")
	@WebResult(name = "SetExchangeMemberCancelResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetExchangeMemberCancel", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberCancel")
	@ResponseWrapper(localName = "SetExchangeMemberCancelResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberCancelResponse")
	public String setExchangeMemberCancel(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetExchangeMemberPassword", action = "http://tempuri.org/IThirdpartyService/SetExchangeMemberPassword")
	@WebResult(name = "SetExchangeMemberPasswordResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetExchangeMemberPassword", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberPassword")
	@ResponseWrapper(localName = "SetExchangeMemberPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetExchangeMemberPasswordResponse")
	public String setExchangeMemberPassword(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetUnitPotoCol", action = "http://tempuri.org/IThirdpartyService/SetUnitPotoCol")
	@WebResult(name = "SetUnitPotoColResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetUnitPotoCol", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitPotoCol")
	@ResponseWrapper(localName = "SetUnitPotoColResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitPotoColResponse")
	public String setUnitPotoCol(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetUnitCollection", action = "http://tempuri.org/IThirdpartyService/SetUnitCollection")
	@WebResult(name = "SetUnitCollectionResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetUnitCollection", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitCollection")
	@ResponseWrapper(localName = "SetUnitCollectionResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitCollectionResponse")
	public String setUnitCollection(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUnitAccount", action = "http://tempuri.org/IThirdpartyService/GetUnitAccount")
	@WebResult(name = "GetUnitAccountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUnitAccount", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetUnitAccount")
	@ResponseWrapper(localName = "GetUnitAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetUnitAccountResponse")
	public String getUnitAccount(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param dcmessage
	 * @param jsmessage
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetUnitAccount", action = "http://tempuri.org/IThirdpartyService/SetUnitAccount")
	@WebResult(name = "SetUnitAccountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetUnitAccount", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitAccount")
	@ResponseWrapper(localName = "SetUnitAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitAccountResponse")
	public String setUnitAccount(
			@WebParam(name = "dcmessage", targetNamespace = "http://tempuri.org/") String dcmessage,
			@WebParam(name = "jsmessage", targetNamespace = "http://tempuri.org/") String jsmessage);

	/**
	 * 
	 * @param hotelname
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GethHotelcodeNew", action = "http://tempuri.org/IThirdpartyService/GethHotelcodeNew")
	@WebResult(name = "GethHotelcodeNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GethHotelcodeNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GethHotelcodeNew")
	@ResponseWrapper(localName = "GethHotelcodeNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GethHotelcodeNewResponse")
	public String gethHotelcodeNew(
			@WebParam(name = "hotelname", targetNamespace = "http://tempuri.org/") String hotelname);

	/**
	 * 
	 * @param hotelname
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GethHotelcode", action = "http://tempuri.org/IThirdpartyService/GethHotelcode")
	@WebResult(name = "GethHotelcodeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GethHotelcode", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GethHotelcode")
	@ResponseWrapper(localName = "GethHotelcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GethHotelcodeResponse")
	public String gethHotelcode(
			@WebParam(name = "hotelname", targetNamespace = "http://tempuri.org/") String hotelname);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Setaccounts", action = "http://tempuri.org/IThirdpartyService/Setaccounts")
	@WebResult(name = "SetaccountsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Setaccounts", targetNamespace = "http://tempuri.org/", className = "com.jte.client.Setaccounts")
	@ResponseWrapper(localName = "SetaccountsResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetaccountsResponse")
	public String setaccounts(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMediPotolCol", action = "http://tempuri.org/IThirdpartyService/SetMediPotolCol")
	@WebResult(name = "SetMediPotolColResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMediPotolCol", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMediPotolCol")
	@ResponseWrapper(localName = "SetMediPotolColResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMediPotolColResponse")
	public String setMediPotolCol(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param hotelcode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Getstandard", action = "http://tempuri.org/IThirdpartyService/Getstandard")
	@WebResult(name = "GetstandardResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Getstandard", targetNamespace = "http://tempuri.org/", className = "com.jte.client.Getstandard")
	@ResponseWrapper(localName = "GetstandardResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetstandardResponse")
	public String getstandard(
			@WebParam(name = "hotelcode", targetNamespace = "http://tempuri.org/") String hotelcode);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAccountsYue", action = "http://tempuri.org/IThirdpartyService/GetAccountsYue")
	@WebResult(name = "GetAccountsYueResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetAccountsYue", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetAccountsYue")
	@ResponseWrapper(localName = "GetAccountsYueResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetAccountsYueResponse")
	public String getAccountsYue(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUnitPotoCol", action = "http://tempuri.org/IThirdpartyService/GetUnitPotoCol")
	@WebResult(name = "GetUnitPotoColResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUnitPotoCol", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetUnitPotoCol")
	@ResponseWrapper(localName = "GetUnitPotoColResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetUnitPotoColResponse")
	public String getUnitPotoCol(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMediPotoCol", action = "http://tempuri.org/IThirdpartyService/GetMediPotoCol")
	@WebResult(name = "GetMediPotoColResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMediPotoCol", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMediPotoCol")
	@ResponseWrapper(localName = "GetMediPotoColResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMediPotoColResponse")
	public String getMediPotoCol(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetUnitMdiAccounts", action = "http://tempuri.org/IThirdpartyService/SetUnitMdiAccounts")
	@WebResult(name = "SetUnitMdiAccountsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetUnitMdiAccounts", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitMdiAccounts")
	@ResponseWrapper(localName = "SetUnitMdiAccountsResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetUnitMdiAccountsResponse")
	public String setUnitMdiAccounts(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendDesindOutRoom", action = "http://tempuri.org/IThirdpartyService/SendDesindOutRoom")
	@WebResult(name = "SendDesindOutRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendDesindOutRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendDesindOutRoom")
	@ResponseWrapper(localName = "SendDesindOutRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendDesindOutRoomResponse")
	public String sendDesindOutRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendProocessByRoom", action = "http://tempuri.org/IThirdpartyService/SendProocessByRoom")
	@WebResult(name = "SendProocessByRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendProocessByRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendProocessByRoom")
	@ResponseWrapper(localName = "SendProocessByRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendProocessByRoomResponse")
	public String sendProocessByRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetStateByRoom", action = "http://tempuri.org/IThirdpartyService/GetStateByRoom")
	@WebResult(name = "GetStateByRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetStateByRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetStateByRoom")
	@ResponseWrapper(localName = "GetStateByRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetStateByRoomResponse")
	public String getStateByRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReserve", action = "http://tempuri.org/IThirdpartyService/GetReserve")
	@WebResult(name = "GetReserveResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReserve", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetReserve")
	@ResponseWrapper(localName = "GetReserveResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetReserveResponse")
	public String getReserve(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetRoomType", action = "http://tempuri.org/IThirdpartyService/GetRoomType")
	@WebResult(name = "GetRoomTypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetRoomType", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomType")
	@ResponseWrapper(localName = "GetRoomTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomTypeResponse")
	public String getRoomType(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetRoomPrice", action = "http://tempuri.org/IThirdpartyService/GetRoomPrice")
	@WebResult(name = "GetRoomPriceResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetRoomPrice", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPrice")
	@ResponseWrapper(localName = "GetRoomPriceResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPriceResponse")
	public String getRoomPrice(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CheckInRoom", action = "http://tempuri.org/IThirdpartyService/CheckInRoom")
	@WebResult(name = "CheckInRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CheckInRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckInRoom")
	@ResponseWrapper(localName = "CheckInRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckInRoomResponse")
	public String checkInRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CheckInRoomNew", action = "http://tempuri.org/IThirdpartyService/CheckInRoomNew")
	@WebResult(name = "CheckInRoomNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CheckInRoomNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckInRoomNew")
	@ResponseWrapper(localName = "CheckInRoomNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckInRoomNewResponse")
	public String checkInRoomNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AgainCheckInroom", action = "http://tempuri.org/IThirdpartyService/AgainCheckInroom")
	@WebResult(name = "AgainCheckInroomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AgainCheckInroom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.AgainCheckInroom")
	@ResponseWrapper(localName = "AgainCheckInroomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.AgainCheckInroomResponse")
	public String againCheckInroom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SaveOutByroom", action = "http://tempuri.org/IThirdpartyService/SaveOutByroom")
	@WebResult(name = "SaveOutByroomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SaveOutByroom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SaveOutByroom")
	@ResponseWrapper(localName = "SaveOutByroomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SaveOutByroomResponse")
	public String saveOutByroom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetLeavemessage", action = "http://tempuri.org/IThirdpartyService/GetLeavemessage")
	@WebResult(name = "GetLeavemessageResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetLeavemessage", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetLeavemessage")
	@ResponseWrapper(localName = "GetLeavemessageResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetLeavemessageResponse")
	public String getLeavemessage(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMemberType", action = "http://tempuri.org/IThirdpartyService/SetMemberType")
	@WebResult(name = "SetMemberTypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMemberType", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberType")
	@ResponseWrapper(localName = "SetMemberTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberTypeResponse")
	public String setMemberType(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ThirdSetMemberGuest", action = "http://tempuri.org/IThirdpartyService/ThirdSetMemberGuest")
	@WebResult(name = "ThirdSetMemberGuestResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ThirdSetMemberGuest", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ThirdSetMemberGuest")
	@ResponseWrapper(localName = "ThirdSetMemberGuestResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ThirdSetMemberGuestResponse")
	public String thirdSetMemberGuest(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/getRoomStatus")
	@WebResult(name = "getRoomStatusResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getRoomStatus", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomStatus")
	@ResponseWrapper(localName = "getRoomStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomStatusResponse")
	public String getRoomStatus(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/getRoomStatusNew")
	@WebResult(name = "getRoomStatusNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getRoomStatusNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomStatusNew")
	@ResponseWrapper(localName = "getRoomStatusNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomStatusNewResponse")
	public String getRoomStatusNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/payBookGold")
	@WebResult(name = "payBookGoldResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "payBookGold", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGold")
	@ResponseWrapper(localName = "payBookGoldResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGoldResponse")
	public String payBookGold(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/checkMemberWx")
	@WebResult(name = "checkMemberWxResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "checkMemberWx", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckMemberWx")
	@ResponseWrapper(localName = "checkMemberWxResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckMemberWxResponse")
	public String checkMemberWx(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/checkMember")
	@WebResult(name = "checkMemberResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "checkMember", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckMember")
	@ResponseWrapper(localName = "checkMemberResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CheckMemberResponse")
	public String checkMember(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/getOrderInfo")
	@WebResult(name = "getOrderInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getOrderInfo", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrderInfo")
	@ResponseWrapper(localName = "getOrderInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetOrderInfoResponse")
	public String getOrderInfo(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/getBottomPrice")
	@WebResult(name = "getBottomPriceResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getBottomPrice", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetBottomPrice")
	@ResponseWrapper(localName = "getBottomPriceResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetBottomPriceResponse")
	public String getBottomPrice(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/createBookrq")
	@WebResult(name = "createBookrqResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "createBookrq", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateBookrq")
	@ResponseWrapper(localName = "createBookrqResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateBookrqResponse")
	public String createBookrq(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateMemberGuest", action = "http://tempuri.org/IThirdpartyService/UpdateMemberGuest")
	@WebResult(name = "UpdateMemberGuestResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdateMemberGuest", targetNamespace = "http://tempuri.org/", className = "com.jte.client.UpdateMemberGuest")
	@ResponseWrapper(localName = "UpdateMemberGuestResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.UpdateMemberGuestResponse")
	public String updateMemberGuest(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CancelBookrq", action = "http://tempuri.org/IThirdpartyService/CancelBookrq")
	@WebResult(name = "CancelBookrqResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CancelBookrq", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CancelBookrq")
	@ResponseWrapper(localName = "CancelBookrqResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CancelBookrqResponse")
	public String cancelBookrq(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/setReserveroom")
	@WebResult(name = "setReserveroomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setReserveroom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetReserveroom")
	@ResponseWrapper(localName = "setReserveroomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetReserveroomResponse")
	public String setReserveroom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/reserveCheckInRoom")
	@WebResult(name = "reserveCheckInRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reserveCheckInRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ReserveCheckInRoom")
	@ResponseWrapper(localName = "reserveCheckInRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ReserveCheckInRoomResponse")
	public String reserveCheckInRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/reserveCheckInRoomNew")
	@WebResult(name = "reserveCheckInRoomNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reserveCheckInRoomNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ReserveCheckInRoomNew")
	@ResponseWrapper(localName = "reserveCheckInRoomNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ReserveCheckInRoomNewResponse")
	public String reserveCheckInRoomNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param hotelcode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetSpacialPlanpriceCode", action = "http://tempuri.org/IThirdpartyService/GetSpacialPlanpriceCode")
	@WebResult(name = "GetSpacialPlanpriceCodeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSpacialPlanpriceCode", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetSpacialPlanpriceCode")
	@ResponseWrapper(localName = "GetSpacialPlanpriceCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetSpacialPlanpriceCodeResponse")
	public String getSpacialPlanpriceCode(
			@WebParam(name = "hotelcode", targetNamespace = "http://tempuri.org/") String hotelcode);

	/**
	 * 
	 * @param hotelcode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetZcodePlanPriceCode", action = "http://tempuri.org/IThirdpartyService/GetZcodePlanPriceCode")
	@WebResult(name = "GetZcodePlanPriceCodeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetZcodePlanPriceCode", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetZcodePlanPriceCode")
	@ResponseWrapper(localName = "GetZcodePlanPriceCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetZcodePlanPriceCodeResponse")
	public String getZcodePlanPriceCode(
			@WebParam(name = "hotelcode", targetNamespace = "http://tempuri.org/") String hotelcode);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.Boolean
	 */
	@WebMethod(operationName = "IsExistsAccounts", action = "http://tempuri.org/IThirdpartyService/IsExistsAccounts")
	@WebResult(name = "IsExistsAccountsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "IsExistsAccounts", targetNamespace = "http://tempuri.org/", className = "com.jte.client.IsExistsAccounts")
	@ResponseWrapper(localName = "IsExistsAccountsResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.IsExistsAccountsResponse")
	public Boolean isExistsAccounts(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetHistoryOrder", action = "http://tempuri.org/IThirdpartyService/GetHistoryOrder")
	@WebResult(name = "GetHistoryOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetHistoryOrder", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetHistoryOrder")
	@ResponseWrapper(localName = "GetHistoryOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetHistoryOrderResponse")
	public String getHistoryOrder(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendIdentificatioinByCard", action = "http://tempuri.org/IThirdpartyService/SendIdentificatioinByCard")
	@WebResult(name = "SendIdentificatioinByCardResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendIdentificatioinByCard", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendIdentificatioinByCard")
	@ResponseWrapper(localName = "SendIdentificatioinByCardResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendIdentificatioinByCardResponse")
	public String sendIdentificatioinByCard(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMemberStoreActive", action = "http://tempuri.org/IThirdpartyService/GetMemberStoreActive")
	@WebResult(name = "GetMemberStoreActiveResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMemberStoreActive", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMemberStoreActive")
	@ResponseWrapper(localName = "GetMemberStoreActiveResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetMemberStoreActiveResponse")
	public String getMemberStoreActive(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendtateByCard", action = "http://tempuri.org/IThirdpartyService/SendtateByCard")
	@WebResult(name = "SendtateByCardResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendtateByCard", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendtateByCard")
	@ResponseWrapper(localName = "SendtateByCardResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendtateByCardResponse")
	public String sendtateByCard(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMemberCoustomerNew", action = "http://tempuri.org/IThirdpartyService/SetMemberCoustomerNew")
	@WebResult(name = "SetMemberCoustomerNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMemberCoustomerNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberCoustomerNew")
	@ResponseWrapper(localName = "SetMemberCoustomerNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberCoustomerNewResponse")
	public String setMemberCoustomerNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/createGuest")
	@WebResult(name = "createGuestResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "createGuest", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateGuest")
	@ResponseWrapper(localName = "createGuestResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateGuestResponse")
	public String createGuest(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/selectGuest")
	@WebResult(name = "selectGuestResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "selectGuest", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SelectGuest")
	@ResponseWrapper(localName = "selectGuestResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SelectGuestResponse")
	public String selectGuest(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/sendService")
	@WebResult(name = "sendServiceResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "sendService", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendService")
	@ResponseWrapper(localName = "sendServiceResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SendServiceResponse")
	public String sendService(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/payBookGoldByMember")
	@WebResult(name = "payBookGoldByMemberResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "payBookGoldByMember", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGoldByMember")
	@ResponseWrapper(localName = "payBookGoldByMemberResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGoldByMemberResponse")
	public String payBookGoldByMember(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/payBookGoldByMemberNew")
	@WebResult(name = "payBookGoldByMemberNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "payBookGoldByMemberNew", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGoldByMemberNew")
	@ResponseWrapper(localName = "payBookGoldByMemberNewResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayBookGoldByMemberNewResponse")
	public String payBookGoldByMemberNew(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/setRoomStates")
	@WebResult(name = "setRoomStatesResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setRoomStates", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetRoomStates")
	@ResponseWrapper(localName = "setRoomStatesResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetRoomStatesResponse")
	public String setRoomStates(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/payThirdParty")
	@WebResult(name = "payThirdPartyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "payThirdParty", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayThirdParty")
	@ResponseWrapper(localName = "payThirdPartyResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.PayThirdPartyResponse")
	public String payThirdParty(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/queryGuestByIn")
	@WebResult(name = "queryGuestByInResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "queryGuestByIn", targetNamespace = "http://tempuri.org/", className = "com.jte.client.QueryGuestByIn")
	@ResponseWrapper(localName = "queryGuestByInResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.QueryGuestByInResponse")
	public String queryGuestByIn(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/refundThirdParty")
	@WebResult(name = "refundThirdPartyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "refundThirdParty", targetNamespace = "http://tempuri.org/", className = "com.jte.client.RefundThirdParty")
	@ResponseWrapper(localName = "refundThirdPartyResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.RefundThirdPartyResponse")
	public String refundThirdParty(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/cancelThirdParty")
	@WebResult(name = "cancelThirdPartyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "cancelThirdParty", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CancelThirdParty")
	@ResponseWrapper(localName = "cancelThirdPartyResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CancelThirdPartyResponse")
	public String cancelThirdParty(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SetMemberMoneyWechat", action = "http://tempuri.org/IThirdpartyService/SetMemberMoneyWechat")
	@WebResult(name = "SetMemberMoneyWechatResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetMemberMoneyWechat", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberMoneyWechat")
	@ResponseWrapper(localName = "SetMemberMoneyWechatResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetMemberMoneyWechatResponse")
	public String setMemberMoneyWechat(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetRoomPlanPriceSpecial", action = "http://tempuri.org/IThirdpartyService/GetRoomPlanPriceSpecial")
	@WebResult(name = "GetRoomPlanPriceSpecialResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetRoomPlanPriceSpecial", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPlanPriceSpecial")
	@ResponseWrapper(localName = "GetRoomPlanPriceSpecialResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPlanPriceSpecialResponse")
	public String getRoomPlanPriceSpecial(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetRoomPlanByHour", action = "http://tempuri.org/IThirdpartyService/GetRoomPlanByHour")
	@WebResult(name = "GetRoomPlanByHourResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetRoomPlanByHour", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPlanByHour")
	@ResponseWrapper(localName = "GetRoomPlanByHourResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPlanByHourResponse")
	public String getRoomPlanByHour(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetRoomPriceByLadder", action = "http://tempuri.org/IThirdpartyService/GetRoomPriceByLadder")
	@WebResult(name = "GetRoomPriceByLadderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetRoomPriceByLadder", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPriceByLadder")
	@ResponseWrapper(localName = "GetRoomPriceByLadderResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.GetRoomPriceByLadderResponse")
	public String getRoomPriceByLadder(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/setTogetherByRoom")
	@WebResult(name = "setTogetherByRoomResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setTogetherByRoom", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetTogetherByRoom")
	@ResponseWrapper(localName = "setTogetherByRoomResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetTogetherByRoomResponse")
	public String setTogetherByRoom(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/setGift")
	@WebResult(name = "setGiftResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setGift", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetGift")
	@ResponseWrapper(localName = "setGiftResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.SetGiftResponse")
	public String setGift(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/createBooksByMoreRoomtype")
	@WebResult(name = "createBooksByMoreRoomtypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "createBooksByMoreRoomtype", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateBooksByMoreRoomtype")
	@ResponseWrapper(localName = "createBooksByMoreRoomtypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.CreateBooksByMoreRoomtypeResponse")
	public String createBooksByMoreRoomtype(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

	/**
	 * 
	 * @param message
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/IThirdpartyService/modifyBookByMoreRoomtype")
	@WebResult(name = "modifyBookByMoreRoomtypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "modifyBookByMoreRoomtype", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ModifyBookByMoreRoomtype")
	@ResponseWrapper(localName = "modifyBookByMoreRoomtypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jte.client.ModifyBookByMoreRoomtypeResponse")
	public String modifyBookByMoreRoomtype(
			@WebParam(name = "message", targetNamespace = "http://tempuri.org/") String message);

}
