
package com.cn.umessage.dao.psb.yichang.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServicePortType", targetNamespace = "http://service.tch.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServicePortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:test")
    @WebResult(targetNamespace = "http://service.tch.com")
    @RequestWrapper(localName = "test", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.TestResponse")
    public String test();

    /**
     * 
     * @param birthday
     * @param sex
     * @param phone
     * @param expired
     * @param sphoto
     * @param pid
     * @param photo
     * @param nation
     * @param hotelno
     * @param djsj
     * @param roomno
     * @param address
     * @param name
     * @param cflag
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:gnlkAdd")
    @WebResult(targetNamespace = "http://service.tch.com")
    @RequestWrapper(localName = "gnlkAdd", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.GnlkAdd")
    @ResponseWrapper(localName = "gnlkAddResponse", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.GnlkAddResponse")
    public String gnlkAdd(
        @WebParam(name = "name", targetNamespace = "http://service.tch.com")
        String name,
        @WebParam(name = "sex", targetNamespace = "http://service.tch.com")
        String sex,
        @WebParam(name = "nation", targetNamespace = "http://service.tch.com")
        String nation,
        @WebParam(name = "birthday", targetNamespace = "http://service.tch.com")
        String birthday,
        @WebParam(name = "expired", targetNamespace = "http://service.tch.com")
        String expired,
        @WebParam(name = "pid", targetNamespace = "http://service.tch.com")
        String pid,
        @WebParam(name = "djsj", targetNamespace = "http://service.tch.com")
        String djsj,
        @WebParam(name = "hotelno", targetNamespace = "http://service.tch.com")
        String hotelno,
        @WebParam(name = "roomno", targetNamespace = "http://service.tch.com")
        String roomno,
        @WebParam(name = "phone", targetNamespace = "http://service.tch.com")
        String phone,
        @WebParam(name = "address", targetNamespace = "http://service.tch.com")
        String address,
        @WebParam(name = "photo", targetNamespace = "http://service.tch.com")
        String photo,
        @WebParam(name = "sphoto", targetNamespace = "http://service.tch.com")
        String sphoto,
        @WebParam(name = "cflag", targetNamespace = "http://service.tch.com")
        String cflag);

    /**
     * 
     * @param hotelno
     * @param djsj
     * @param tfsj
     * @param pid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:checkOut")
    @WebResult(targetNamespace = "http://service.tch.com")
    @RequestWrapper(localName = "checkOut", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.CheckOut")
    @ResponseWrapper(localName = "checkOutResponse", targetNamespace = "http://service.tch.com", className = "com.cn.umessage.dao.psb.yichang.wsClient.CheckOutResponse")
    public String checkOut(
        @WebParam(name = "pid", targetNamespace = "http://service.tch.com")
        String pid,
        @WebParam(name = "djsj", targetNamespace = "http://service.tch.com")
        String djsj,
        @WebParam(name = "tfsj", targetNamespace = "http://service.tch.com")
        String tfsj,
        @WebParam(name = "hotelno", targetNamespace = "http://service.tch.com")
        String hotelno);

}
